{{$swagTagName := .SwaggerTagName}}
swagger: "2.0"
info:
  title: Welcome to Apic
  description: APIS generated by apic
  version: 1.0.0
host: {{ .HostName}}:{{ .Port}}
basePath: /
tags:
  - name: {{ .SwaggerTagName}}
    description: {{ .SwaggerTagDesc}}
schemes:
  - http
paths:
  {{ with .RestApis }}
   {{ range . }}
   {{ .Path}}:
      get:
        tags:
        - {{ $swagTagName }}
        summary: {{ .SwagDesc}}
        description: {{ .SwagDesc}}
        produces:
          - application/json
        responses:
          200:
           description: "OK, successful"
           schema:
             type: "object"
      post:
        tags:
        - {{ $swagTagName }}
        summary: {{ .SwagDesc}} (insert)
        description: {{ .SwagDesc}}
        operationId: {{ .OperationId}}
        consumes:
        - "application/json"
        parameters:
        - in: "body"
          name: "jsonObject"
          description: "Json object to insert"
          required: true
          schema:
            type: "object"
        responses:
          '201':
            description: "Created"
      put:
        tags:
        - {{ $swagTagName }}
        summary: {{ .SwagDesc}} (update)
        description: {{ .SwagDesc}}
        operationId: {{ .OperationId}}
        consumes:
        - "application/json"
        parameters:
        - in: "body"
          name: "jsonObject"
          description: "Json object to update"
          schema:
            type: "string"
        responses:
          '201':
            description: "Updated"
      delete:
        tags:
        - {{ $swagTagName }}
        summary: {{ .SwagDesc}} (delete)
        description: {{ .SwagDesc}}
        operationId: {{ .OperationId}}
        consumes:
        - "application/json"
        parameters:
        - name: "id"
          in: "path"
          description: "entity id to delete"
          schema:
            type: "string"
        responses:
          '201':
            description: "Deleted"
   {{end}}
  {{end}}
