swagger: "2.0"
info:
  title: apic generated APIs
  description: 
  version: 1.0.0
host: {{ .hostName}}
basePath: /
schemes:
  - http
paths:
  {{range .apiCmds}}
  {{.path}}:
      get:
        summary: {{ .description}}
        description: {{ .description}}
        produces:
          - application/json
      responses:
        200:
          description: OK
  {{end}}