{{$swagTagName := .SwaggerTagName}}
swagger: "2.0"
info:
  title: Welcome to Apic
  description: APIS generated by apic
  version: 1.0.0
host: {{ .HostName}}
basePath: /
tags:
  - name: {{ .SwaggerTagName}}
    description: {{ .SwaggerTagDesc}}
schemes:
  - http
paths:
  {{ with .RestApis }}
   {{ range . }}
   {{ .Path}}:
      get:
        tags:
        - {{ $swagTagName }}
        summary: {{ .SwagDesc}}
        description: {{ .SwagDesc}}
        produces:
          - application/json
        responses:
          200:
           description: "OK, successful"
           schema:
             type: "object"
      post:
        tags:
        - {{ $swagTagName }}
        summary: {{ .SwagDesc}}
        description: {{ .SwagDesc}}
        operationId: {{ .OperationId}}
        consumes:
        - "application/json"
        parameters:
        - in: "body"
          name: "body"
          description: {{ .SwagDesc}}
          required: true
          schema:
            type: "object"
        responses:
          '201':
            description: "Created"
   {{end}}
  {{end}}
